config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  resources :orders
  resources :pizzas, only: [:index]
  resources :recipes
  resources :ingredients
  resources :crusts

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: 'pizzas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/crust.rb
class Crust < ApplicationRecord
end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:typecrust, :value)
    end
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/views/crusts/_form.html.erb
<%= form_with(model: crust, local: true) do |form| %>
  <% if crust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crust.errors.count, "error") %> prohibited this crust from being saved:</h2>

      <ul>
      <% crust.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :typecrust %>
    <%= form.text_field :typecrust, id: :crust_typecrust %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :crust_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crusts/edit.html.erb
<h1>Editing Crust</h1>

<%= render 'form', crust: @crust %>

<%= link_to 'Show', @crust %> |
<%= link_to 'Back', crusts_path %>

app/views/crusts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crusts</h1>

<table>
  <thead>
    <tr>
      <th>Typecrust</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crusts.each do |crust| %>
      <tr>
        <td><%= crust.typecrust %></td>
        <td><%= crust.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/crusts/new.html.erb
<h1>New Crust</h1>

<%= render 'form', crust: @crust %>

<%= link_to 'Back', crusts_path %>

app/views/crusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typecrust:</strong>
  <%= @crust.typecrust %>
</p>

<p>
  <strong>Value:</strong>
  <%= @crust.value %>
</p>

<%= link_to 'Edit', edit_crust_path(@crust) %> |
<%= link_to 'Back', crusts_path %>